sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t aroweb/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true aroweb/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react"
  name: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-central-1-313706048276"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

   

